name: jsonplaceholder_flutterconfig
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  logger: ^1.1.0
  get: ^4.6.5
  flutter_slidable: ^1.3.1
  flutter_config: ^2.0.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

assets:
  #   - images/a_dot_ham.jpeg


fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
